In [1]:
import pandas as pd
import os
os.chdir('..')
from src.data.data_trans import *

In [2]:
def convertions(row):
        if row['unit_1'] == 'kg':
            return row['qty'] * 1
        elif row['unit_1'] == 'l':
            return row['qty'] * 1
        elif row['unit_1'] == 'doz':
            return row['qty'] / 0.756
        elif row['unit_1'] =='m3':
            return row['qty'] * 1560
        elif row['unit_1'] == 't':
            return row['qty'] * 907.185
        elif row['unit_1'] == 'kts':
            return row['qty'] * 1
        elif row['unit_1'] == 'pfl':
            return row['qty'] * 0.789
        elif row['unit_1'] == 'gm':
            return row['qty'] * 1000
        else:
            return np.nan

In [3]:
import pandas as pd

# Sample DataFrame
data = {'category_name': ['A', 'B', 'A', 'B', 'C'],
        'quantity': [10, 15, 20, 25, 30]}
df = pd.DataFrame(data)

# Define a custom transformation function
def transform_quantity(row):
    if row['category_name'] == 'A':
        return row['quantity'] * 2  # Double quantity for category A
    elif row['category_name'] == 'B':
        return row['quantity'] * 1.5  # Increase quantity by 50% for category B
    else:
        return row['quantity']  # No transformation for other categories

# Apply the transformation to the 'quantity' column
df['transformed_quantity'] = df.apply(transform_quantity, axis=1)

# Display the result
print(df)

  category_name  quantity  transformed_quantity
0             A        10                  20.0
1             B        15                  22.5
2             A        20                  40.0
3             B        25                  37.5
4             C        30                  30.0

In [4]:
df, df2= DataTrans(data_path="data/raw/imports_data.csv").clean(debug=True)
df2

,import_export,country,value,unit_1,unit_2,HTS,HTS_desc,date,HTS_dummy,qty
0,i,United States,490253.0,kg,NaN,0201,Carcasses and Half-Carcasses of Bovine Animals...,2002-07-01,0201100090,165763.0
1,i,United States,933406.0,kg,NaN,0201,"Meat of Bovines, With Bone In, Processed, Fres...",2002-07-01,0201203550,507174.0
2,i,United States,1391780.0,kg,NaN,0201,"Meat of Bovines, With Bone In, Fresh or Chille...",2002-07-01,0201206000,437346.0
3,i,United States,1742546.0,kg,NaN,0201,"Meat of Bovines, Boneless, Processed, Fresh or...",2002-07-01,0201303550,724552.0
4,i,Nicaragua,148795.0,kg,NaN,0201,"Meat of Bovines, Boneless, Fresh or Chilled, A...",2002-07-01,0201305000,38962.0
...,...,...,...,...,...,...,...,...,...,...
343663,i,United States,8838.0,gm,NaN,2941,Erythromycin and Its Derivatives; Salts Thereof,2023-06-01,2941500000,12000000.0
343664,i,United States,18000.0,kg,NaN,2941,Aminoglycoside Antibiotics,2023-06-01,2941901010,14.0
343665,i,Croatia,2695770.0,kg,NaN,2941,"Other Antibiotics (Excluding Natural, Aromatic...",2023-06-01,2941905000,10890.0
343666,i,United States,163932.0,kg,NaN,2941,Antibiotics Nesoi,2023-06-01,2941906000,230.0
343667,i,United States,12180.0,kg,NaN,2942,Organic Compounds Nesoi,2023-06-01,2942000000,11.0

In [10]:
df_dev = df.copy()
# sort by lowest qty
df_dev.sort_values(by='qty', ascending=True, inplace=True)
df_dev

,date,HTS,qty,value,value_growth,value_per_unit,name,parent_HTS,parent_name
17293,2003-09-01,2209,1.578000e+00,4494.0,-0.873927,2847.908745,Vinegar and Substitutes for Vinegar Obtained F...,22,"Beverages, Spirits and Vinegar"
4172,2016-05-01,1209,3.000000e+00,9450.0,-0.888370,3150.000000,"Seeds, Fruit and Spores, of A Kind Used for So...",12,Oil Seeds and Oleaginous Fruits; Miscellaneous...
4248,2022-09-01,1209,4.000000e+00,27486.0,-0.715109,6871.500000,"Seeds, Fruit and Spores, of A Kind Used for So...",12,Oil Seeds and Oleaginous Fruits; Miscellaneous...
18844,2019-07-01,1504,1.700000e+01,3357.0,0.000000,197.470588,"Fats and Oils and Their Fractions, of Fish or ...",15,"Animal, Vegetable or Microbial Fats and Oils a..."
18843,2019-05-01,1504,1.700000e+01,3357.0,0.000000,197.470588,"Fats and Oils and Their Fractions, of Fish or ...",15,"Animal, Vegetable or Microbial Fats and Oils a..."
...,...,...,...,...,...,...,...,...,...
257,2013-02-01,1004,2.655204e+09,1200720.0,85.557093,0.000452,Oats,10,Cereals
266,2014-11-01,1004,2.917824e+09,1131756.0,112.652942,0.000388,Oats,10,Cereals
261,2014-05-01,1004,3.429206e+09,1607556.0,46.938093,0.000469,Oats,10,Cereals
282,2017-02-01,1004,4.898863e+09,1317388.0,31.787158,0.000269,Oats,10,Cereals
269,2015-07-01,1004,4.989006e+09,1115503.0,110.061629,0.000224,Oats,10,Cereals

In [6]:
df_iterm = df2.copy()
df_iterm = df_iterm[df_iterm['unit_1'] == 'gm']
df_iterm

,import_export,country,value,unit_1,unit_2,HTS,HTS_desc,date,HTS_dummy,qty
1139,i,United States,109353.0,gm,NaN,2937,"Somatotropin, Its Derivatives and Structural A...",2002-07-01,2937110000,72900000.0
1140,i,United States,5760.0,gm,NaN,2937,Insulin and Its Salts,2002-07-01,2937120000,11001000.0
1141,i,United States,195228.0,gm,NaN,2937,"Cortisone, Hydrocortisone, Prednisone and Pred...",2002-07-01,2937210000,322002000.0
1142,i,United States,1052058.0,gm,NaN,2937,Halogenated Derivatives of Adrenal Cortical Ho...,2002-07-01,2937220000,109564000.0
1143,i,United States,62000.0,gm,NaN,2937,Estrogens and Progestins,2002-07-01,2937230000,20000000.0
...,...,...,...,...,...,...,...,...,...,...
343650,i,United States,2650.0,gm,NaN,2937,Amino-Acid Derivatives,2023-06-01,2937903000,5000000.0
343652,i,United States,139068.0,gm,NaN,2937,"Hormones, Prostaglandins, Thromboxanes and Leu...",2023-06-01,2937909000,44000000.0
343654,i,United States,44540.0,gm,NaN,2939,Concentrates of Poppy Straw; Buprenorphine (In...,2023-06-01,2939110000,1746000.0
343655,i,United States,2800.0,gm,NaN,2939,"Alkaloids of Opium and Their Derivatives, Salt...",2023-06-01,2939190000,2000000.0
343663,i,United States,8838.0,gm,NaN,2941,Erythromycin and Its Derivatives; Salts Thereof,2023-06-01,2941500000,12000000.0